// ============================================
// RAG Security Knowledge Base -- Neo4j Import
// Version: 5.2.0 (generated from CSV datasets)
// Entities: RAG, Surface (8), Attack (38), Risk (41), Weakness (12 CWE), Mitigation (72), CIA
// Generated by: generate_import_cypher.py
// Source CSVs: risks, mitigations, attacks, surfaces, weaknesses, enables, corrects
// ============================================

// --- CLEAN DATABASE ---
MATCH (n) DETACH DELETE n;

// --- CONSTRAINTS ---
CREATE CONSTRAINT IF NOT EXISTS FOR (n:RAG) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Surface) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Attack) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Risk) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Weakness) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Mitigation) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:CIA) REQUIRE n.id IS UNIQUE;

// --- INDEXES ---
CREATE INDEX IF NOT EXISTS FOR (r:Risk) ON (r.category);
CREATE INDEX IF NOT EXISTS FOR (r:Risk) ON (r.asset);
CREATE INDEX IF NOT EXISTS FOR (a:Attack) ON (a.category);
CREATE INDEX IF NOT EXISTS FOR (m:Mitigation) ON (m.type);
CREATE INDEX IF NOT EXISTS FOR (w:Weakness) ON (w.type);

// --- RAG VARIANTS (3) ---
UNWIND [
  {id: 'TEXTUAL', name: 'Textual RAG', description: 'Classic textual RAG (merging Naive + Advanced + Modular). Pipeline: Indexation -> Retrieval -> Generation on textual documents.', source: 'Gao et al. 2024 (arXiv:2312.10997)'},
  {id: 'GRAPHRAG', name: 'GraphRAG', description: 'Knowledge-graph-based RAG. Adds KG-specific surfaces (M3.graph) to textual surfaces.', source: 'Edge et al. 2024 (Microsoft GraphRAG)'},
  {id: 'MULTIMODAL', name: 'Multimodal RAG', description: 'Multimodal RAG processing text, images and audio. Inherits textual surfaces and adds M3.multi.', source: 'Meta-Model Synthesis v5.0'}
] AS props
CREATE (n:RAG) SET n = props;

// --- NOTE: Category is an attribute of Attack (not a separate entity) ---
// Categories: INJ (Injection), POI (Poisoning), INF (Inference),
//             EXF (Exfiltration), DEG (Degradation), UNK (Unknown)

// --- SURFACES (8) ---
UNWIND [
  {id: 'M1', name: 'Document Acquisition', type: 'DOCUMENT', description: 'Document ingestion into the RAG pipeline', source: 'Lewis et al. 2020, OWASP Attack Surface Analysis', code: 'S-DOC', module: 'M1'},
  {id: 'M2', name: 'Preprocessing / Normalization', type: 'DOCUMENT', description: 'Parsing, chunking, and cleaning of ingested documents', source: 'Gao et al. 2024, LlamaIndex Node Parsers', module: 'M2'},
  {id: 'M3', name: 'Indexation (Vector Store)', type: 'DATABASE', description: 'Embedding encoding and vector storage', source: 'Johnson et al. 2019 (FAISS), Gao et al. 2024', module: 'M3'},
  {id: 'M4', name: 'Query Optimization', type: 'API', description: 'Rewriting and expansion of the user query', source: 'Ma et al. 2023, Gao et al. 2024', code: 'S-QUERY', module: 'M4'},
  {id: 'M5', name: 'Retrieval', type: 'API', description: 'Relevant document search in the vector store', source: 'Lewis et al. 2020, Karpukhin et al. 2020 (DPR)', code: 'S-RETR', module: 'M5'},
  {id: 'M6', name: 'Post-Retrieval (reranking filtering)', type: 'API', description: 'Reranking and filtering of retrieved documents', source: 'Glass et al. 2022, Gao et al. 2024', module: 'M6'},
  {id: 'M7', name: 'Generation (LLM)', type: 'API', description: 'Response generation by the LLM', source: 'Lewis et al. 2020', code: 'S-GEN', module: 'M7'},
  {id: 'Tx', name: 'Cross-cutting Modules', type: 'SYSTEM', description: 'Conversational memory, orchestration, monitoring', source: 'Park et al. 2023, LangChain Agents', module: 'Tx'}
] AS props
CREATE (n:Surface) SET n = props;

// --- WEAKNESSES / CWE (12) ---
// Aligned with SYNTHESE v5.0 Table 4.2b (Category -> CWE -> CAPEC mapping)
UNWIND [
  {id: 'CWE-74', name: 'Improper Neutralization of Special Elements in Output Used by a Downstream Component', source: 'MITRE CWE', severity: 4, capec: 'CAPEC-242'},
  {id: 'CWE-94', name: 'Improper Control of Generation of Code (Code Injection)', source: 'MITRE CWE', severity: 4, capec: 'CAPEC-242'},
  {id: 'CWE-200', name: 'Exposure of Sensitive Information to an Unauthorized Actor', source: 'MITRE CWE', severity: 3, capec: 'CAPEC-116, CAPEC-118'},
  {id: 'CWE-203', name: 'Observable Discrepancy', source: 'MITRE CWE', severity: 2, capec: 'CAPEC-116'},
  {id: 'CWE-212', name: 'Improper Removal of Sensitive Information Before Storage or Transfer', source: 'MITRE CWE', severity: 3, capec: 'CAPEC-118'},
  {id: 'CWE-345', name: 'Insufficient Verification of Data Authenticity', source: 'MITRE CWE', severity: 3, capec: 'CAPEC-141'},
  {id: 'CWE-400', name: 'Uncontrolled Resource Consumption', source: 'MITRE CWE', severity: 3, capec: 'CAPEC-125'},
  {id: 'CWE-693', name: 'Protection Mechanism Failure', source: 'MITRE CWE', severity: 4, capec: 'CAPEC-242'},
  {id: 'CWE-770', name: 'Allocation of Resources Without Limits or Throttling', source: 'MITRE CWE', severity: 3, capec: 'CAPEC-125'},
  {id: 'CWE-863', name: 'Incorrect Authorization', source: 'MITRE CWE', severity: 4, capec: 'CAPEC-242'},
  {id: 'CWE-1321', name: 'Improperly Controlled Modification of Object Prototype Attributes (Prototype Pollution)', source: 'MITRE CWE', severity: 3, capec: 'CAPEC-141'},
  {id: 'CWE-1427', name: 'Improper Neutralization of Input Used for LLM Prompting', source: 'MITRE CWE', severity: 5, capec: 'CAPEC-242'}
] AS props
CREATE (n:Weakness) SET n = props;

// --- ATTACKS (38) ---
UNWIND [
  {id: 'ATT.INJ.1', name: 'Indirect prompt injection', category: 'INJ', risk_id: 'R9', source: 'Ammann et al. 2025', external_ref: 'CAPEC-242'},
  {id: 'ATT.INJ.2', name: 'Indirect jailbreak attack', category: 'INJ', risk_id: 'R10', source: 'Ammann et al. 2025', external_ref: 'CAPEC-122'},
  {id: 'ATT.INJ.3', name: 'Confused deputy & access control exploitation', category: 'INJ', risk_id: 'R18', source: 'RoyChowdhury et al. (ConfusedPilot)', external_ref: 'CAPEC-242'},
  {id: 'ATT.INJ.4', name: 'Direct LLM manipulation attack', category: 'INJ', risk_id: 'R21', source: 'Li et al. (Targeting the Core)', external_ref: 'CAPEC-242'},
  {id: 'ATT.POI.1', name: 'Knowledge corruption attack', category: 'POI', risk_id: 'R8', source: 'Ammann et al. 2025', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.2', name: 'Data loader poisoning (Unicode invisible)', category: 'POI', risk_id: 'R11', source: 'Hidden Threat & RAG-PULL', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.3', name: 'Low-level perturbation attack', category: 'POI', risk_id: 'R12', source: 'Typos that Broke the RAG\'s Back', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.4', name: 'Fairness-driven backdoor attack', category: 'POI', risk_id: 'R13', source: 'BiasRAG', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.5', name: 'Few-shot knowledge poisoning', category: 'POI', risk_id: 'R15', source: 'ADMIT', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.6', name: 'Knowledge graph poisoning', category: 'POI', risk_id: 'R17', source: 'RAG Safety', external_ref: 'CAPEC-141', rag_specific: 'GRAPHRAG'},
  {id: 'ATT.POI.7', name: 'RAG Paradox (exposed sources)', category: 'POI', risk_id: 'R19', source: 'Choi et al. (RAG Paradox)', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.8', name: 'Stealth passage poisoning', category: 'POI', risk_id: 'R20', source: 'Choudhary et al. (Stealth Lens)', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.9', name: 'Bias amplification poisoning', category: 'POI', risk_id: 'R23', source: 'Wang et al. (Bias Amplification)', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.10', name: 'Multimodal poisoning attack', category: 'POI', risk_id: 'R24', source: 'Yu et al. (Spa-VLM)', external_ref: 'CAPEC-141', rag_specific: 'MULTIMODAL'},
  {id: 'ATT.POI.11', name: 'Cross-modal knowledge poisoning', category: 'POI', risk_id: 'R29', source: 'Ha et al. (MM-PoisonRAG)', external_ref: 'CAPEC-141', rag_specific: 'MULTIMODAL'},
  {id: 'ATT.POI.12', name: 'Topic-level opinion manipulation', category: 'POI', risk_id: 'R30', source: 'Gong et al. (Topic-FlipRAG)', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.13', name: 'Retrieval backdoor attack (BadRAG)', category: 'POI', risk_id: 'R32', source: 'Xue et al. (BadRAG)', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.14', name: 'Silver noise attack', category: 'POI', risk_id: 'R33', source: 'Liang et al. (SafeRAG)', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.15', name: 'Inter-context conflict attack', category: 'POI', risk_id: 'R34', source: 'Liang et al. (SafeRAG)', external_ref: 'CAPEC-141'},
  {id: 'ATT.POI.16', name: 'Soft ad attack', category: 'POI', risk_id: 'R35', source: 'Liang et al. (SafeRAG)', external_ref: 'CAPEC-141'},
  {id: 'ATT.INF.1', name: 'Membership inference attack', category: 'INF', risk_id: 'R4', source: 'Anderson et al. 2024', external_ref: 'CAPEC-116'},
  {id: 'ATT.INF.2', name: 'Generation budget side channel', category: 'INF', risk_id: 'R16', source: 'BudgetLeak', external_ref: 'CAPEC-116'},
  {id: 'ATT.INF.3', name: 'Cross-modal membership leakage', category: 'INF', risk_id: 'R25', source: 'Sun et al. (SMA)', external_ref: 'CAPEC-116', rag_specific: 'MULTIMODAL'},
  {id: 'ATT.INF.4', name: 'Interrogation attack (stealthy MIA)', category: 'INF', risk_id: 'R37', source: 'Naseh et al. 2025', external_ref: 'CAPEC-116'},
  {id: 'ATT.INF.5', name: 'Multimodal MIA (MrM)', category: 'INF', risk_id: 'R39', source: 'Yang et al. (MrM)', external_ref: 'CAPEC-116', rag_specific: 'MULTIMODAL'},
  {id: 'ATT.EXF.1', name: 'Retrieval data leakage', category: 'EXF', risk_id: 'R2', source: 'Ammann et al. 2025', external_ref: 'CAPEC-118'},
  {id: 'ATT.EXF.2', name: 'Embedding inversion attack', category: 'EXF', risk_id: 'R3', source: 'Ammann et al. 2025', external_ref: 'CAPEC-118'},
  {id: 'ATT.EXF.3', name: 'Retrieval data disclosure during embedding', category: 'EXF', risk_id: 'R5', source: 'Ammann et al. 2025', external_ref: 'CAPEC-118'},
  {id: 'ATT.EXF.4', name: 'Retrieval data disclosure during prompting', category: 'EXF', risk_id: 'R6', source: 'Ammann et al. 2025', external_ref: 'CAPEC-118'},
  {id: 'ATT.EXF.5', name: 'Prompt disclosure', category: 'EXF', risk_id: 'R7', source: 'Ammann et al. 2025', external_ref: 'CAPEC-118'},
  {id: 'ATT.EXF.6', name: 'Implicit knowledge extraction (IKEA)', category: 'EXF', risk_id: 'R14', source: 'Silent Leaks (IKEA)', external_ref: 'CAPEC-118'},
  {id: 'ATT.EXF.7', name: 'Adaptive knowledge extraction', category: 'EXF', risk_id: 'R22', source: 'Maio et al. (Pirates of the RAG)', external_ref: 'CAPEC-118'},
  {id: 'ATT.EXF.8', name: 'Internal oversharing & data amplification', category: 'EXF', risk_id: 'R27', source: 'CWE-212 / CAPEC-118', external_ref: 'CAPEC-118'},
  {id: 'ATT.EXF.9', name: 'Adversarial string extraction (MARAGE)', category: 'EXF', risk_id: 'R31', source: 'Hu et al. (MARAGE)', external_ref: 'CAPEC-118'},
  {id: 'ATT.EXF.10', name: 'Embedding information leakage', category: 'EXF', risk_id: 'R38', source: 'Song & Raghunathan 2020', external_ref: 'CAPEC-118'},
  {id: 'ATT.EXF.11', name: 'Knowledge base extraction attack', category: 'EXF', risk_id: 'R40', source: 'Jiang et al. 2024', external_ref: 'CAPEC-118'},
  {id: 'ATT.DEG.1', name: 'System limitation exploitation', category: 'DEG', risk_id: 'R1', source: 'Ammann et al. 2025', external_ref: 'CAPEC-125'},
  {id: 'ATT.DEG.2', name: 'White denial-of-service attack', category: 'DEG', risk_id: 'R36', source: 'Liang et al. (SafeRAG)', external_ref: 'CAPEC-125'}
] AS props
CREATE (n:Attack) SET n = props;

// --- RISKS (41) -- 38 with attack, 3 without (R0, R26, R28) ---
UNWIND [
  {id: 'R0', name: 'Emerging zero-day risks (blind spot)', name_technique: 'Unknown Risk (Blind Spot)', category: 'UNK', cia: 'C; I; A', asset: 'CORPUS', assets: ['CORPUS', 'OUTPUT', 'MEMBERSHIP', 'EMBEDDINGS', 'PROMPTS'], description: 'Unidentified or emerging risks (zero-day) that have not yet been anticipated or cataloged.', source: 'Ammann et al. 2025', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'https://doi.org/10.1109/SDS66131.2025.00024', has_attack: false},
  {id: 'R1', name: 'Output degradation via system limitations', name_technique: 'System limitation', category: 'DEG', cia: 'A', asset: 'OUTPUT', assets: ['OUTPUT'], description: 'The RAG system cannot handle complex data or tasks beyond its design limits, leading to degraded performance.', source: 'Ammann et al.', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'https://doi.org/10.1109/SDS66131.2025.00024', has_attack: true},
  {id: 'R2', name: 'Corpus data leakage via retrieval component', name_technique: 'Retrieval data leakage', category: 'EXF', cia: 'C', asset: 'CORPUS', assets: ['CORPUS'], description: 'Sensitive data from the document corpus is leaked through the retrieval component.', source: 'Ammann et al. 2025', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'https://doi.org/10.1109/SDS66131.2025.00024', has_attack: true},
  {id: 'R3', name: 'Original text reconstruction from embeddings via inversion', name_technique: 'Embedding inversion attack', category: 'INF', cia: 'C', asset: 'EMBEDDINGS', assets: ['EMBEDDINGS'], description: 'Original text is reconstructed from embedding vectors via inversion attacks.', source: 'Ammann et al. 2025', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'https://doi.org/10.1109/SDS66131.2025.00024', has_attack: true},
  {id: 'R4', name: 'Membership disclosure via inference attack', name_technique: 'Membership inference attack', category: 'INF', cia: 'C', asset: 'MEMBERSHIP', assets: ['MEMBERSHIP'], description: 'An attacker infers whether a specific document belongs to the corpus (membership inference).', source: 'Ammann et al. 2025', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'https://doi.org/10.1109/SDS66131.2025.00024', has_attack: true},
  {id: 'R5', name: 'Sensitive data exposure during embedding encoding', name_technique: 'Retrieval data disclosure during embedding', category: 'EXF', cia: 'C', asset: 'EMBEDDINGS', assets: ['EMBEDDINGS'], description: 'Sensitive data is exposed during the embedding encoding process.', source: 'Ammann et al. 2025', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'https://doi.org/10.1109/SDS66131.2025.00024', has_attack: true},
  {id: 'R6', name: 'Corpus disclosure during generation', name_technique: 'Retrieval data disclosure during prompting', category: 'EXF', cia: 'C', asset: 'CORPUS', assets: ['CORPUS'], description: 'Corpus data is disclosed during the generation phase via retrieved passages.', source: 'Ammann et al. 2025', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'https://doi.org/10.1109/SDS66131.2025.00024', has_attack: true},
  {id: 'R7', name: 'Prompts disclosure to unauthorized users', name_technique: 'Prompt disclosure', category: 'EXF', cia: 'C', asset: 'PROMPTS', assets: ['PROMPTS'], description: 'System prompt instructions are disclosed to unauthorized users.', source: 'Ammann et al. 2025', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'https://doi.org/10.1109/SDS66131.2025.00024', has_attack: true},
  {id: 'R8', name: 'Corpus corruption via malicious ingestion', name_technique: 'Knowledge corruption attack', category: 'POI', cia: 'I', asset: 'CORPUS', assets: ['CORPUS'], description: 'Corpus integrity is altered through malicious document ingestion.', source: 'Ammann et al. 2025', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'https://doi.org/10.1109/SDS66131.2025.00024', has_attack: true},
  {id: 'R9', name: 'Output manipulation via indirect prompt injection', name_technique: 'Indirect prompt injection', category: 'INJ', cia: 'I', asset: 'OUTPUT', assets: ['OUTPUT'], description: 'Unauthorized behavior modification via instructions injected into retrieved documents.', source: 'Ammann et al. 2025', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'https://doi.org/10.1109/SDS66131.2025.00024', has_attack: true},
  {id: 'R10', name: 'Output guardrail bypass via jailbreak content', name_technique: 'Indirect jailbreak attack', category: 'INJ', cia: 'I', asset: 'OUTPUT', assets: ['OUTPUT'], description: 'Safety guardrails are bypassed via adversarial content in retrieved documents.', source: 'Ammann et al. 2025', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'https://doi.org/10.1109/SDS66131.2025.00024', has_attack: true},
  {id: 'R11', name: 'Corpus corruption via invisible Unicode injection', name_technique: 'Data loader poisoning / Invisible injection', category: 'POI', cia: 'I', asset: 'CORPUS', assets: ['CORPUS'], description: 'Corpus corruption via invisible Unicode characters injected in documents.', source: 'Hidden Threat & RAG-PULL', arxiv: 'https://arxiv.org/abs/2507.05093; https://arxiv.org/abs/2510.11195', conference: 'https://doi.org/10.1145/3733799.3762976', has_attack: true},
  {id: 'R12', name: 'Corpus integrity degradation via low-level text perturbations', name_technique: 'Low-level perturbation attack', category: 'POI', cia: 'I', asset: 'CORPUS', assets: ['CORPUS'], description: 'Retrieval degradation through minor textual perturbations (typos, homoglyphs).', source: 'Typos that Broke the RAG’s Back', arxiv: 'https://arxiv.org/abs/2404.13948', conference: 'https://aclanthology.org/2024.findings-emnlp.161/', has_attack: true},
  {id: 'R13', name: 'Corpus bias induction via fairness backdoor', name_technique: 'Fairness-driven backdoor attack', category: 'POI', cia: 'I', asset: 'CORPUS', assets: ['CORPUS'], description: 'Discriminatory biases are induced via backdoor patterns injected in the corpus.', source: 'BiasRAG', arxiv: 'https://arxiv.org/abs/2509.22486', conference: 'https://aclanthology.org/2025.emnlp-main.804/', has_attack: true},
  {id: 'R14', name: 'Corpus stealthy extraction via semantic anchoring', name_technique: 'Implicit knowledge extraction attack', category: 'INF', cia: 'C', asset: 'CORPUS', assets: ['CORPUS'], description: 'Stealthy extraction of sensitive information through semantic anchoring queries.', source: 'Silent Leaks (IKEA)', arxiv: 'https://arxiv.org/abs/2505.15420', conference: 'https://icml.cc/virtual/2025/50943', has_attack: true},
  {id: 'R15', name: 'Corpus misinformation via few-shot poisoning', name_technique: 'Few-shot knowledge poisoning', category: 'POI', cia: 'I', asset: 'CORPUS', assets: ['CORPUS'], description: 'Misinformation propagation through injection of adversarial passages.', source: 'ADMIT', arxiv: 'https://arxiv.org/abs/2510.13842', conference: '', has_attack: true},
  {id: 'R16', name: 'Membership inference via budget side channel', name_technique: 'Generation budget side channel', category: 'INF', cia: 'C', asset: 'MEMBERSHIP', assets: ['MEMBERSHIP'], description: 'Membership inference via side-channel observation of generation token budget.', source: 'BudgetLeak', arxiv: 'https://arxiv.org/abs/2511.12043', conference: '', has_attack: true},
  {id: 'R17', name: 'Corpus manipulation via knowledge graph poisoning', name_technique: 'Knowledge graph poisoning', category: 'POI', cia: 'I', asset: 'CORPUS', assets: ['CORPUS'], description: 'Reasoning path manipulation via injection of false triples in the knowledge graph.', source: 'RAG Safety', arxiv: 'https://arxiv.org/abs/2507.08862', conference: 'https://doi.org/10.1016/j.inffus.2025.103900', has_attack: true},
  {id: 'R18', name: 'Output integrity and confidentiality compromise via confused deputy', name_technique: 'Confused deputy & access control exploitation', category: 'INJ', cia: 'I; C', asset: 'OUTPUT', assets: ['OUTPUT', 'CORPUS'], description: 'Access control bypass through malicious priority documents (confused deputy).', source: 'RoyChowdhury et al. (ConfusedPilot)', arxiv: 'https://arxiv.org/abs/2408.04870', conference: '', has_attack: true},
  {id: 'R19', name: 'Corpus exposure via retrieved source attribution', name_technique: 'RAG Paradox (exposed retrieval and source information)', category: 'EXF', cia: 'C', asset: 'CORPUS', assets: ['CORPUS'], description: 'Poisoning facilitated by exposing retrieved source information to the user.', source: 'Choi et al. (RAG Paradox)', arxiv: 'https://arxiv.org/abs/2502.20995', conference: 'https://aclanthology.org/2025.findings-emnlp.1291/', has_attack: true},
  {id: 'R20', name: 'Corpus corruption via stealth passage mimicry', name_technique: 'Stealth passage poisoning', category: 'POI', cia: 'I', asset: 'CORPUS', assets: ['CORPUS'], description: 'Stealthy result corruption via passages that mimic normal documents.', source: 'Choudhary et al. (Stealth Lens)', arxiv: 'https://arxiv.org/abs/2506.04390', conference: '', has_attack: true},
  {id: 'R21', name: 'Output manipulation via adversarial prefix injection', name_technique: 'Direct LLM manipulation attack', category: 'INJ', cia: 'I', asset: 'OUTPUT', assets: ['OUTPUT'], description: 'Retrieved documents are forcibly ignored via adversarial prefix injection into the LLM.', source: 'Li et al. (Targeting the Core)', arxiv: 'https://arxiv.org/abs/2412.04415', conference: '', has_attack: true},
  {id: 'R22', name: 'Corpus extraction via adaptive queries', name_technique: 'Adaptive knowledge extraction attack', category: 'INF', cia: 'C', asset: 'CORPUS', assets: ['CORPUS'], description: 'Progressive knowledge base extraction through adaptive query strategies.', source: 'Maio et al. (Pirates of the RAG)', arxiv: 'https://arxiv.org/abs/2412.18295', conference: 'https://ebooks.iospress.nl/doi/10.3233/FAIA251293', has_attack: true},
  {id: 'R23', name: 'Output bias amplification via embedding manipulation', name_technique: 'Bias amplification poisoning', category: 'POI', cia: 'I', asset: 'OUTPUT', assets: ['OUTPUT'], description: 'Social bias amplification through manipulation of the embedding space.', source: 'Wang et al. (Bias Amplification)', arxiv: 'https://arxiv.org/abs/2506.11415', conference: '', has_attack: true},
  {id: 'R24', name: 'Corpus corruption via deceptive multimodal injection', name_technique: 'Multimodal poisoning attack', category: 'POI', cia: 'I', asset: 'CORPUS', assets: ['CORPUS'], description: 'Response corruption through injection of deceptive images and text (multimodal RAG).', source: 'Yu et al. (Spa‑VLM)', arxiv: 'https://arxiv.org/abs/2505.23828', conference: '', has_attack: true},
  {id: 'R25', name: 'Membership inference via cross-modal opacity', name_technique: 'Cross-modal membership leakage', category: 'INF', cia: 'C', asset: 'MEMBERSHIP', assets: ['MEMBERSHIP'], description: 'Multimodal membership inference exploiting cross-modal opacity.', source: 'Sun et al. (SMA)', arxiv: 'https://arxiv.org/abs/2508.09105', conference: '', has_attack: true},
  {id: 'R26', name: 'Output integrity risk from human overreliance', name_technique: 'Overreliance & Automation Bias', category: 'DEG', cia: 'I', asset: 'OUTPUT', assets: ['OUTPUT'], description: 'Error acceptance due to excessive trust in AI-generated outputs (human factor).', source: 'NIST AI 600-1 (2024)', arxiv: 'https://doi.org/10.6028/NIST.AI.600-1', conference: 'NIST (2024)', has_attack: false},
  {id: 'R27', name: 'Corpus sensitive data exposure via excessive indexing', name_technique: 'Internal Oversharing & Data Amplification', category: 'EXF', cia: 'C', asset: 'CORPUS', assets: ['CORPUS'], description: 'Sensitive document exposure through over-indexing of the corpus.', source: 'CWE-212 / OWASP LLM Top 10 (2025)', arxiv: 'https://cwe.mitre.org/data/definitions/212.html', conference: 'CWE/OWASP (2025)', has_attack: true},
  {id: 'R28', name: 'Output availability risk from vendor dependency', name_technique: 'Vendor Transparency & Infrastructure Dependency', category: 'DEG', cia: 'A; C', asset: 'OUTPUT', assets: ['OUTPUT'], description: 'Unavailability or loss of control due to external LLM vendor dependency.', source: 'NIST AI 600-1 (2024)', arxiv: 'https://doi.org/10.6028/NIST.AI.600-1', conference: 'NIST (2024)', has_attack: false},
  {id: 'R29', name: 'Corpus perturbation via cross-modal poisoning', name_technique: 'Cross-Modal Knowledge Poisoning', category: 'POI', cia: 'I', asset: 'CORPUS', assets: ['CORPUS'], description: 'Reasoning perturbation through external multimodal injection (MM-RAG).', source: 'Ha et al. (MM-PoisonRAG)', arxiv: 'https://arxiv.org/abs/2502.17832', conference: '', has_attack: true},
  {id: 'R30', name: 'Output opinion manipulation via thematic poisoning', name_technique: 'Topic-Level Opinion Manipulation', category: 'POI', cia: 'I', asset: 'OUTPUT', assets: ['OUTPUT'], description: 'Model opinion manipulation through thematic corpus poisoning.', source: 'Gong et al. (Topic-FlipRAG)', arxiv: 'https://arxiv.org/abs/2502.01386', conference: 'https://dl.acm.org/doi/10.5555/3766078.3766274', has_attack: true},
  {id: 'R31', name: 'Corpus verbatim extraction via adversarial strings', name_technique: 'Adversarial String Extraction (MARAGE)', category: 'EXF', cia: 'C', asset: 'CORPUS', assets: ['CORPUS'], description: 'Verbatim document extraction through adversarial string injection.', source: 'Hu et al. (MARAGE)', arxiv: 'https://arxiv.org/abs/2502.04360', conference: '', has_attack: true},
  {id: 'R32', name: 'Corpus corruption via query-embedded backdoor triggers', name_technique: 'Retrieval Backdoor Attack', category: 'POI', cia: 'I', asset: 'CORPUS', assets: ['CORPUS'], description: 'Backdoor activation through trigger patterns embedded in queries.', source: 'Xue et al. (BadRAG)', arxiv: 'https://arxiv.org/abs/2406.00083', conference: '', has_attack: true},
  {id: 'R33', name: 'Corpus integrity degradation via silver noise injection', name_technique: 'Silver Noise Attack', category: 'POI', cia: 'I', asset: 'CORPUS', assets: ['CORPUS'], description: 'Retrieval degradation through partially correct evidence (silver noise).', source: 'Liang et al. (SafeRAG)', arxiv: 'https://arxiv.org/abs/2501.18636', conference: 'https://aclanthology.org/2025.acl-long.230/', has_attack: true},
  {id: 'R34', name: 'Output corruption via inter-source contradictions', name_technique: 'Inter-Context Conflict Attack', category: 'POI', cia: 'I', asset: 'OUTPUT', assets: ['OUTPUT'], description: 'Incorrect response generation caused by inter-source contradictions.', source: 'Liang et al. (SafeRAG)', arxiv: 'https://arxiv.org/abs/2501.18636', conference: 'https://aclanthology.org/2025.acl-long.230/', has_attack: true},
  {id: 'R35', name: 'Output contamination via covert advertising injection', name_technique: 'Soft Ad Attack', category: 'POI', cia: 'I', asset: 'OUTPUT', assets: ['OUTPUT'], description: 'Implicit advertising content injection into generated responses.', source: 'Liang et al. (SafeRAG)', arxiv: 'https://arxiv.org/abs/2501.18636', conference: 'https://aclanthology.org/2025.acl-long.230/', has_attack: true},
  {id: 'R36', name: 'Output suppression via fake security warnings', name_technique: 'White Denial-of-Service (DoS) Attack', category: 'DEG', cia: 'I', asset: 'OUTPUT', assets: ['OUTPUT'], description: 'Response refusal induced by fake security warnings (white DoS).', source: 'Liang et al. (SafeRAG)', arxiv: 'https://arxiv.org/abs/2501.18636', conference: 'https://aclanthology.org/2025.acl-long.230/', has_attack: true},
  {id: 'R37', name: 'Membership inference via interrogation queries', name_technique: 'Interrogation Attack (Stealthy Membership Inference)', category: 'INF', cia: 'C', asset: 'MEMBERSHIP', assets: ['MEMBERSHIP'], description: 'Membership inference through targeted natural language interrogation queries.', source: 'Naseh et al. 2025', arxiv: 'https://arxiv.org/abs/2502.00306', conference: 'https://doi.org/10.1145/3719027.3744840', has_attack: true},
  {id: 'R38', name: 'Embeddings information leakage via embedding model vulnerabilities', name_technique: 'Embedding Information Leakage', category: 'INF', cia: 'C', asset: 'EMBEDDINGS', assets: ['EMBEDDINGS'], description: 'Sensitive information leakage through embedding model vulnerabilities.', source: 'Song & Raghunathan 2020', arxiv: 'https://arxiv.org/abs/2004.00053', conference: 'https://doi.org/10.1145/3372297.3417270', has_attack: true},
  {id: 'R39', name: 'Membership inference via multimodal perturbation and masking', name_technique: 'Multimodal Membership Inference Attack (MrM)', category: 'INF', cia: 'C', asset: 'MEMBERSHIP', assets: ['MEMBERSHIP'], description: 'Image membership inference through perturbation and masking attacks.', source: 'Yang et al. (MrM)', arxiv: 'https://arxiv.org/abs/2506.07399', conference: '', has_attack: true},
  {id: 'R40', name: 'Corpus knowledge base extraction via progressive queries', name_technique: 'Knowledge Base Extraction Attack (Inter-class & Intra-class)', category: 'INF', cia: 'C', asset: 'CORPUS', assets: ['CORPUS'], description: 'Knowledge base reconstruction through progressive extraction queries.', source: 'Jiang et al. 2024', arxiv: 'https://arxiv.org/abs/2411.14110', conference: '', has_attack: true}
] AS props
CREATE (n:Risk) SET n = props;

// --- MITIGATIONS (72) ---
UNWIND [
  {id: 'MIT0', name: 'Anonymization', type: 'PREVENTIVE', active: true, category: 'Secure retrieval', description: 'Remove personally identifiable information from documents before ingestion to prevent leakage of sensitive data.', source: 'Ammann et al. 2025', arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT1', name: 'Pseudonymization', type: 'PREVENTIVE', active: true, category: 'Secure retrieval', description: 'Replace sensitive identifiers with reversible placeholders to allow future re‑identification while protecting privacy.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT2', name: 'Synthetic data', type: 'PREVENTIVE', active: true, category: 'Secure retrieval', description: 'Generate synthetic training data to augment or replace real data, reducing exposure of actual records.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT3', name: 'Access limitation', type: 'PREVENTIVE', active: true, category: 'System hardening', description: 'Limit who or what can write or access the retrieval database; enforce access control policies to reduce corruption or leakage.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT4', name: 'Reinforcement of system instructions', type: 'PREVENTIVE', active: true, category: 'System hardening', description: 'Strengthen system prompts and safety instructions to constrain the model’s responses and prevent exploitation through retrieved content.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT5', name: 'Input validation', type: 'PREVENTIVE', active: true, category: 'System hardening', description: 'Validate and sanitize inputs and retrieved content to detect and remove malicious patterns or instructions.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT6', name: 'Evaluation framework', type: 'DETECTIVE', active: true, category: 'System hardening', description: 'Establish systematic evaluation for retrieval and generation, including monitoring retrieval quality and detection of malicious content.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT7', name: 'Self‑hosting AI models', type: 'PREVENTIVE', active: true, category: 'Privacy and control', description: 'Host AI models locally or in trusted environments to avoid exposure through third‑party APIs and reduce vulnerability during embedding.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT8', name: 'Adding noise', type: 'PREVENTIVE', active: true, category: 'Privacy and control', description: 'Add random noise to embeddings or retrieval results to obfuscate sensitive data and reduce the risk of embedding inversion.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT9', name: 'Distance threshold', type: 'PREVENTIVE', active: true, category: 'Retrieval control', description: 'Apply a similarity threshold to ensure only highly relevant documents are retrieved, reducing exposure to irrelevant or adversarial data.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT10', name: 'Summarization', type: 'REACTIVE', active: true, category: 'Retrieval control', description: 'Summarize retrieved content before feeding it to the generator, reducing the amount of exposed data and potential for leakage.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT11', name: 'Re‑ranking', type: 'REACTIVE', active: true, category: 'Retrieval control', description: 'Re‑rank retrieved passages based on relevance and quality to filter out adversarial or low‑quality information.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT12', name: 'Minimization of exposure', type: 'PREVENTIVE', active: true, category: 'Privacy and control', description: 'Reduce the scope of user‑facing APIs and minimize the exposure of retrieval and generation functions to mitigate exploitation.', source: null, arxiv: 'https://arxiv.org/abs/2505.08728', conference: 'IEEE SDS 2025 (DOI: 10.1109/SDS66131.2025.00024)'},
  {id: 'MIT13', name: 'Sanitization and anomaly detection for invisible injection', type: 'PREVENTIVE', active: true, category: 'Data ingestion', description: 'Detect anomalous Unicode sequences (diacritical stacking, zero‑width characters, homoglyphs) and bidirectional control characters; apply Unicode normalization, remove zero‑width characters, and use OCR pipelines to strip hidden characters and formatting.', source: 'Hidden Threat & RAG-PULL', arxiv: 'https://arxiv.org/abs/2507.05093', conference: 'ACM AISec 2025 (DOI: 10.1145/3733799.3762976)'},
  {id: 'MIT14', name: 'Perplexity‑based filtering', type: 'DETECTIVE', active: true, category: 'RAG poisoning defense', description: 'Use a perplexity threshold (e.g., 99th percentile) to filter out passages with anomalous language patterns that may indicate poisoning.', source: 'Eyes‑on‑Me', arxiv: 'https://arxiv.org/abs/2510.00586', conference: 'Preprint'},
  {id: 'MIT15', name: 'Paraphrase (query rewriting)', type: 'PREVENTIVE', active: true, category: 'RAG poisoning defense', description: 'Rewrite the input query before retrieval to mitigate optimized attack vectors and reduce the effectiveness of poisoning.', source: null, arxiv: 'https://arxiv.org/abs/2510.00586', conference: 'Preprint'},
  {id: 'MIT16', name: 'Self‑Reminder (defensive prompt)', type: 'PREVENTIVE', active: true, category: 'RAG poisoning defense', description: 'Add defensive instructions to the prompt reminding the model to ignore malicious patterns in the retrieved content.', source: null, arxiv: 'https://arxiv.org/abs/2510.00586', conference: 'Preprint'},
  {id: 'MIT17', name: 'Self‑Examination', type: 'DETECTIVE', active: true, category: 'RAG poisoning defense', description: 'Use a larger language model to self‑check the generated answer and flag or revise outputs based on their alignment with safe behaviors; neutralizes many attacks but incurs high resource cost.', source: null, arxiv: 'https://arxiv.org/abs/2510.00586', conference: 'Preprint'},
  {id: 'MIT18', name: 'Noise insertion', type: 'PREVENTIVE', active: true, category: 'RAG poisoning defense', description: 'Insert random tokens or characters into the input to disrupt the optimized tokens of a poisoning attack, reducing its effectiveness.', source: null, arxiv: 'https://arxiv.org/abs/2510.00586', conference: 'Preprint'},
  {id: 'MIT19', name: 'Grammar checker for low‑level perturbations', type: 'DETECTIVE', active: true, category: 'Low‑level perturbation defense', description: 'Use grammar checkers to detect and remove typos or noisy inputs before ingestion; however, this strategy may drop legitimate text and does not detect all adversarial examples.', source: 'Typos that Broke the RAG’s Back', arxiv: 'https://arxiv.org/abs/2404.13948', conference: 'https://aclanthology.org/2024.findings-emnlp.161/'},
  {id: 'MIT20', name: 'Fairness defense layers', type: 'PREVENTIVE', active: true, category: 'Fairness backdoor defense', description: 'Implement complementary layers such as retriever provenance logging, document trust scoring, protected‑attribute rewriting (removing or anonymizing protected attributes), semantic outlier detection on retrieved results, and post‑generation fairness scans to identify and mitigate unfair backdoor behavior.', source: 'BiasRAG', arxiv: 'https://arxiv.org/abs/2509.22486', conference: 'https://aclanthology.org/2025.emnlp-main.804/'},
  {id: 'MIT21', name: 'BiasDef post‑processing filter', type: 'DETECTIVE', active: true, category: 'Fairness backdoor defense', description: 'Construct a feature space using similarity and perspective scores; apply KL divergence to set a threshold separating benign and adversarial passages; filter out outliers and recover any false negatives to mitigate bias injection attacks.', source: 'BiasDef', arxiv: 'https://arxiv.org/abs/2512.00804', conference: 'Preprint'},
  {id: 'MIT22', name: 'Input‑ and output‑level detection', type: 'DETECTIVE', active: true, category: 'Knowledge extraction defense', description: 'At input level: use intention detection, keyword filtering, and defensive instructions to identify malicious queries; at output level: apply perplexity-based detection, content detection and redaction, and LLM-based filtering to block sensitive information.', source: 'Silent Leaks (IKEA)', arxiv: 'https://arxiv.org/abs/2505.15420', conference: 'https://openreview.net/forum?id=F5TD0OExsf'},
  {id: 'MIT23', name: 'Fake news detection and knowledge consolidation', type: 'DETECTIVE', active: true, category: 'Few‑shot poisoning defense', description: 'Use LLM-based fake‑news detectors (e.g., FakeWatch), divide-and-vote approaches, consolidate‑then‑select strategies, perplexity and ROUGE-based detection, and agent-based frameworks to identify and filter adversarial passages; however, current methods have limited effectiveness against few-shot knowledge poisoning.', source: 'ADMIT', arxiv: 'https://arxiv.org/abs/2510.13842', conference: 'Preprint'},
  {id: 'MIT24', name: 'Response rewriting', type: 'REACTIVE', active: true, category: 'Membership inference defense', description: 'Rewrite the model’s output (instead of the query) using an LLM to distort membership cues and reduce the discriminability of membership signals when using generation budget side channels.', source: 'BudgetLeak', arxiv: 'https://arxiv.org/abs/2511.12043', conference: 'Preprint'},
  {id: 'MIT25', name: 'RAGDEFENDER (clustering & concentration)', type: 'DETECTIVE', active: true, category: 'Knowledge poisoning defense', description: 'Group retrieved passages using clustering and concentration-based algorithms to identify adversarial passages; filter them out without additional LLM inference, significantly reducing attack success and improving robustness.', source: 'Rescuing the Unpoisoned', arxiv: 'https://arxiv.org/abs/2511.01268', conference: 'ACSAC 2025'},
  {id: 'MIT26', name: 'Constrained generation protocol', type: 'PREVENTIVE', active: true, category: 'Generation risk control', description: 'Use parameters such as the number of retrieved examples, generation set size, and similarity threshold to control the generation process; conformal analysis provides an upper bound on generation risk, ensuring reliability even under distribution shifts.', source: 'C-RAG', arxiv: 'https://arxiv.org/abs/2402.03181', conference: 'ICML 2024, PMLR 235'},
  {id: 'MIT27', name: 'Self‑RAG (adaptive retrieval & reflection)', type: 'REACTIVE', active: true, category: 'Adaptive retrieval', description: 'Use self-reflection tokens to indicate when retrieval is needed and critique tokens to evaluate retrieved segments; the model adaptively decides when to retrieve and how to critique its output, improving factuality and reducing exposure.', source: 'Self‑RAG', arxiv: 'https://arxiv.org/abs/2310.11511', conference: 'ICLR 2024 (Oral, top 1%) https://openreview.net/forum?id=hSyW5go0v8'},
  {id: 'MIT28', name: 'MemoRAG (global memory & dual system)', type: 'REACTIVE', active: true, category: 'Adaptive retrieval', description: 'Employ a dual‑system architecture: a lightweight long-range system builds a global memory of the context and provides draft answers, and a more expressive system retrieves information based on those clues to generate the final answer, enabling robust processing of long contexts.', source: 'MemoRAG', arxiv: 'https://arxiv.org/abs/2409.05591', conference: 'TheWebConf (WWW) 2025 (DOI: 10.1145/3696410.3714805)'},
  {id: 'MIT29', name: 'Multi‑agent retrieval', type: 'REACTIVE', active: true, category: 'Adaptive retrieval', description: 'Delegate retrieval tasks to multiple specialized agents (e.g., one per data source or query type); they collaborate within a modular framework to produce more accurate and efficient retrievals, mitigating system limitations and data contamination.', source: 'Multi‑Agent RAG', arxiv: 'https://arxiv.org/abs/2412.05838', conference: null},
  {id: 'MIT30', name: 'Retrieved data & prompt validation', type: 'PREVENTIVE', active: true, category: 'Data ingestion & validation', description: 'Enterprises should validate retrieved documents and prompts for malicious strings before they are used in RAG. Tools like Microsoft Prompt Shield can detect malicious patterns, although false positives may limit legitimate queries.', source: 'RoyChowdhury et al. (ConfusedPilot)', arxiv: 'https://arxiv.org/abs/2408.04870', conference: 'Preprint'},
  {id: 'MIT31', name: 'Information flow control in LLM', type: 'PREVENTIVE', active: true, category: 'System hardening', description: 'Implement dynamic information‑flow control inside the LLM so that its outputs always respect confidentiality and integrity policies, regardless of the retrieval results or user permissions.', source: null, arxiv: 'https://arxiv.org/abs/2408.04870', conference: null},
  {id: 'MIT32', name: 'Stricter access control & cache synchronization', type: 'PREVENTIVE', active: true, category: 'System hardening', description: 'Maintain real‑time synchronization between documents and the retrieval database and enforce strict access control to avoid asynchronous updates and misconfigurations that enable confused‑deputy attacks.', source: null, arxiv: 'https://arxiv.org/abs/2408.04870', conference: null},
  {id: 'MIT33', name: 'Anomaly detection & retrieval filtering', type: 'DETECTIVE', active: true, category: 'Detection & evaluation', description: 'Employ anomaly detection methods to identify unusual retrieval patterns and filter suspicious documents before generation. This helps mitigate RAG Paradox attacks.', source: 'Choi et al. (RAG Paradox)', arxiv: 'https://arxiv.org/abs/2502.20995', conference: 'Findings of EMNLP 2025 https://aclanthology.org/2025.findings-emnlp.1291/'},
  {id: 'MIT34', name: 'Output auditing', type: 'DETECTIVE', active: true, category: 'Detection & evaluation', description: 'Audit generated outputs to determine whether they rely on manipulated or irrelevant sources and adjust retrieval or generation accordingly.', source: null, arxiv: 'https://arxiv.org/abs/2502.20995', conference: 'Findings of EMNLP 2025 https://aclanthology.org/2025.findings-emnlp.1291/'},
  {id: 'MIT35', name: 'Attention‑variance filtering', type: 'DETECTIVE', active: true, category: 'RAG poisoning defense', description: 'Use normalized passage attention scores and an attention variance filter to detect and remove passages with unusually high attention variance, preventing stealth passage poisoning.', source: 'Choudhary et al. (Stealth Lens)', arxiv: 'https://arxiv.org/abs/2506.04390', conference: 'Preprint'},
  {id: 'MIT36', name: 'Database access control', type: 'PREVENTIVE', active: true, category: 'System hardening', description: 'Restrict insertion or modification of knowledge‑base entries to trusted users and compartments, preventing poison documents and worms from entering the RAG data store.', source: 'Cohen et al. (Worms)', arxiv: 'https://arxiv.org/pdf/2409.08045', conference: 'https://dl.acm.org/doi/10.1145/3719027.3765196'},
  {id: 'MIT37', name: 'API throttling', type: 'PREVENTIVE', active: true, category: 'System‑level control', description: 'Limit the number and frequency of queries to RAG systems, making it harder for attackers to probe the system or propagate worms.', source: null, arxiv: 'https://arxiv.org/pdf/2409.08045', conference: 'https://dl.acm.org/doi/10.1145/3719027.3765196'},
  {id: 'MIT38', name: 'Retrieval thresholding', type: 'PREVENTIVE', active: true, category: 'Retrieval control', description: 'Apply minimum similarity thresholds during retrieval to ensure that only highly relevant documents are returned, reducing the chance of retrieving irrelevant or malicious documents.', source: null, arxiv: 'https://arxiv.org/pdf/2409.08045', conference: 'https://dl.acm.org/doi/10.1145/3719027.3765196'},
  {id: 'MIT39', name: 'Human‑in‑the‑loop filtering', type: 'DETECTIVE', active: true, category: 'Human oversight', description: 'Include human validators to review inputs and outputs, detecting malicious prompts or suspicious retrieval results, although scaling such oversight can be challenging.', source: null, arxiv: 'https://arxiv.org/pdf/2409.08045', conference: 'https://dl.acm.org/doi/10.1145/3719027.3765196'},
  {id: 'MIT40', name: 'Input content size limit', type: 'PREVENTIVE', active: true, category: 'System hardening', description: 'Restrict the length of user input prompts to reduce the ability to embed large malicious instructions, helping to prevent jailbreaks and knowledge extraction.', source: null, arxiv: 'https://arxiv.org/pdf/2409.08045', conference: 'https://dl.acm.org/doi/10.1145/3719027.3765196'},
  {id: 'MIT41', name: 'Automatic input/output sanitization', type: 'PREVENTIVE', active: true, category: 'Data ingestion & validation', description: 'Use automatic classifiers and detection tools to sanitize or filter input queries and output responses, removing or flagging suspicious content. This helps reduce knowledge extraction and propagation of worms.', source: null, arxiv: 'https://arxiv.org/pdf/2409.08045', conference: 'https://dl.acm.org/doi/10.1145/3719027.3765196'},
  {id: 'MIT42', name: 'Gradient‑based masked token probability (GMTP)', type: 'DETECTIVE', active: true, category: 'RAG poisoning defense', description: 'Analyze gradient values of the retriever’s similarity function to identify key tokens, mask them, and evaluate masked token probabilities using a language model. Documents with low probabilities are filtered, eliminating over 90% of poisoned content while retaining relevant documents.', source: 'Kim et al. (GMTP)', arxiv: 'https://arxiv.org/abs/2507.18202', conference: 'Findings of ACL 2025 (DOI: 10.18653/v1/2025.findings-acl.1263)'},
  {id: 'MIT43', name: 'Differential privacy & explainable AI at LLM level', type: 'PREVENTIVE', active: true, category: 'Privacy & transparency', description: 'To defend against direct LLM manipulation, integrate differential privacy mechanisms to limit the influence of individual inputs on model outputs, and adopt explainable AI techniques to surface anomalous or adversarially-induced LLM behaviors; identified as future defense directions against prefix injection attacks.', source: 'Li et al. (Targeting the Core)', arxiv: 'https://arxiv.org/abs/2412.04415', conference: 'Preprint'},
  {id: 'MIT44', name: 'Universal adversarial training & real-time anomaly detection', type: 'DETECTIVE', active: true, category: 'System hardening', description: 'Apply universal adversarial training to expose the LLM to diverse adversarial prefix variants during training, building consistent resistance across model implementations; complement with real-time anomaly detection systems that monitor output consistency to flag abnormal responses induced by injection attacks.', source: null, arxiv: 'https://arxiv.org/abs/2412.04415', conference: null},
  {id: 'MIT45', name: 'Retrieval parameter tuning', type: 'REACTIVE', active: true, category: 'Retrieval control', description: 'Adjust retrieval parameters such as top‑k selection, query placeholder position and similarity thresholds to reduce knowledge leakage and hinder adaptive extraction attacks.', source: 'Maio et al. (Pirates of the RAG)', arxiv: 'https://arxiv.org/abs/2412.18295', conference: 'Preprint'},
  {id: 'MIT46', name: 'Position bias elimination & adversarial/differential policy training', type: 'PREVENTIVE', active: true, category: 'System hardening', description: 'For preventing leakage, instruct the generator not to reproduce source documents and combine this with position bias elimination, adversarial training or differential policy training to reduce leakage.', source: 'Arzanipour et al. (RAG Security Survey)', arxiv: 'https://arxiv.org/abs/2509.20324', conference: 'Preprint'},
  {id: 'MIT47', name: 'Scoring‑based filter & retrieval scoring regularization', type: 'DETECTIVE', active: true, category: 'RAG poisoning defense', description: 'Use scoring‑based filters to detect adversarial documents and apply retrieval scoring regularization to penalize documents that produce sharp gradients, smoothing the retriever’s score distribution to mitigate poisoning attacks.', source: null, arxiv: 'https://arxiv.org/abs/2509.20324', conference: null},
  {id: 'MIT48', name: 'Retriever‑level differential privacy & adversarial filtering', type: 'PREVENTIVE', active: true, category: 'Privacy & control', description: 'Integrate differential privacy at the retrieval level and apply adversarial filtering to remove malicious retrieval results; this is highlighted as a promising direction for future research.', source: null, arxiv: 'https://arxiv.org/abs/2509.20324', conference: null},
  {id: 'MIT49', name: 'Query perturbation & multi‑query retrieval', type: 'PREVENTIVE', active: true, category: 'Retrieval control', description: 'Add random perturbations to queries to create multiple query variants and aggregate retrieval results using frequency and ranking metrics. This diversifies retrieval and reduces the probability of retrieving adversarial documents.', source: 'Wang et al. (Bias Amplification)', arxiv: 'https://arxiv.org/abs/2506.11415', conference: 'Preprint'},
  {id: 'MIT50', name: 'Dynamic fairness constraints', type: 'PREVENTIVE', active: true, category: 'Fairness & bias', description: 'Compute fairness scores for different demographic groups in retrieved documents and generate dynamic constraint instructions (strong, moderate, mild) to guide the language model towards balanced outputs. Monitor bias indicators and apply additional constraints when necessary.', source: null, arxiv: 'https://arxiv.org/abs/2506.11415', conference: null},
  {id: 'MIT51', name: 'Cautionary system prompt for membership leakage', type: 'PREVENTIVE', active: true, category: 'Membership & leakage', description: 'Insert a system prompt instructing the model not to reveal membership information of the knowledge base. This naive defense offers limited protection and has little impact on advanced cross‑modal membership attacks.', source: 'Yang et al. (MrM)', arxiv: 'https://arxiv.org/abs/2506.07399', conference: 'Preprint'},
  {id: 'MIT52', name: 'Adversarial training for multimodal models', type: 'PREVENTIVE', active: true, category: 'Multimodal defense', description: 'Apply adversarial training to strengthen visual models against adversarial images. However, training multimodal models with adversarial examples incurs high computational costs and often reduces performance.', source: 'Yu et al. (Spa‑VLM)', arxiv: 'https://arxiv.org/abs/2505.23828', conference: 'Preprint'},
  {id: 'MIT53', name: 'Randomized input preprocessing', type: 'PREVENTIVE', active: true, category: 'Multimodal defense', description: 'Use random resizing and padding operations to preprocess input images, disrupting adversarial perturbations. While simple and plug‑and‑play, this method is ineffective against sophisticated cluster‑based attacks in Spa‑VLM.', source: null, arxiv: 'https://arxiv.org/abs/2505.23828', conference: null},
  {id: 'MIT54', name: 'Paraphrasing target question', type: 'PREVENTIVE', active: true, category: 'Multimodal defense', description: 'Defend against toxic texts by paraphrasing the user’s question and re‑retrieving relevant documents. In Spa‑VLM experiments, paraphrasing fails to reduce the reranking scores of malicious texts.', source: null, arxiv: 'https://arxiv.org/abs/2505.23828', conference: null},
  {id: 'MIT55', name: 'Duplicate text filtering', type: 'DETECTIVE', active: true, category: 'Multimodal defense', description: 'Filter duplicate malicious texts in the retrieved results. In Spa‑VLM, this method fails because the malicious texts remain unique due to diverse outputs from the model.', source: null, arxiv: 'https://arxiv.org/abs/2505.23828', conference: null},
  {id: 'MIT56', name: 'AI Literacy & Cognitive Forcing Functions', type: 'REACTIVE', active: true, category: 'Education & Process', description: 'Provide mandatory AI literacy training tailored to individual traits and emphasise AI fallibility; incorporate continuous reminders and cognitive forcing functions (confidence scores, uncertainty metrics) to encourage critical evaluation of AI outputs.', source: 'NIST AI 600-1 (2024)', arxiv: 'https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf', conference: 'NIST AI 600-1 (2024)'},
  {id: 'MIT57', name: 'Data Governance & Privacy Screeners', type: 'PREVENTIVE', active: true, category: 'Data Governance & Privacy', description: 'Strengthen access governance and data classification to prevent oversharing; use locally hosted privacy screeners to filter sensitive input before it reaches the LLM, shifting oversight from users to system architecture.', source: 'CWE-212 / OWASP LLM Top 10 (2025)', arxiv: 'https://cwe.mitre.org/data/definitions/212.html', conference: 'CWE-212 / OWASP LLM Top 10 (2025)'},
  {id: 'MIT58', name: 'Vendor Audit & Self‑Hosting', type: 'PREVENTIVE', active: true, category: 'Governance & Infrastructure', description: 'Perform due diligence on third-party vendors, require transparent security documentation, and include contractual safeguards; when possible host RAG services within own tenant to retain control and mitigate availability risks.', source: 'NIST AI 600-1 (2024)', arxiv: null, conference: 'NIST AI 600-1 (2024)'},
  {id: 'MIT59', name: 'Cross‑Modal Consistency & Modality‑Specific Defenses', type: 'PREVENTIVE', active: true, category: 'Retrieval & Filtering', description: 'Develop defenses that explicitly verify cross-modal consistency among retrieved image–text pairs and retrain rerankers or generators with robust cross-modal objectives; these measures go beyond text-centric heuristics and help mitigate multimodal knowledge poisoning.', source: 'Ha et al. (MM-PoisonRAG)', arxiv: 'https://arxiv.org/abs/2502.17832', conference: 'Preprint'},
  {id: 'MIT60', name: 'Utility‑Based Filtering & Anomaly Detection', type: 'DETECTIVE', active: true, category: 'Filtering & Detection', description: 'Employ utility-based filtering to rank retrieval results by contribution, use TF‑IDF anomaly detection and intra-top‑k similarity analysis to identify semantic outliers, and develop certified mechanisms grounded in topic and fact consistency to defend against topic-level opinion manipulation.', source: 'Gong et al. (Topic-FlipRAG)', arxiv: 'https://arxiv.org/abs/2502.01386', conference: 'https://dl.acm.org/doi/10.5555/3766078.3766274'},
  {id: 'MIT61', name: 'Adversarial Training & Filter‑Based Defense for Strings', type: 'DETECTIVE', active: true, category: 'Model Training & Filtering', description: 'Tailor adversarial training to detect adversarial strings appended to queries, enhancing the model’s ability to ignore such patterns; complement with filter-based defenses that verify outputs for parts resembling the RAG data and use perplexity-based checks to detect adversarial inputs.', source: 'Hu et al. (MARAGE)', arxiv: 'https://arxiv.org/abs/2502.04360', conference: null},
  {id: 'MIT62', name: 'Prompt Paraphrasing & Modification', type: 'PREVENTIVE', active: true, category: 'Retrieval & Generation', description: 'Rewrite queries to mislead the retriever and prevent retrieval of the original sample; modify prompts to instruct the LLM to summarise rather than repeat retrieved content, effectively mitigating membership inference attacks.', source: 'Li et al. (S2MIA)', arxiv: 'https://arxiv.org/abs/2406.19234', conference: 'Preprint'},
  {id: 'MIT63', name: 'Mask‑Based Trigger Detection', type: 'DETECTIVE', active: true, category: 'Retrieval Filtering', description: 'Detect retrieval backdoors by replacing tokens in queries with [MASK] and observing changes in retrieval similarity; significant drops indicate the presence of trigger words; single-token masking works for single-token triggers, while two-token masking helps detect multi-token triggers.', source: 'Xue et al. (BadRAG)', arxiv: 'https://arxiv.org/abs/2406.00083', conference: 'Preprint'},
  {id: 'MIT64', name: 'Random Projection for Differential Privacy', type: 'PREVENTIVE', active: true, category: 'Privacy Preservation', description: 'Project queries and datastore into a lower-dimensional space using Gaussian matrices to achieve (ε, δ)-differential privacy, blurring sensitive information while preserving retrieval quality.', source: 'Yao & Li (Private RAG)', arxiv: null, conference: 'https://openreview.net/forum?id=lX5xDv2X8N'},
  {id: 'MIT65', name: 'Synthetic Data Generation (SAGE)', type: 'PREVENTIVE', active: true, category: 'Data Sanitation & Replacement', description: 'Use a two-stage synthetic data pipeline: extract key attributes from sensitive data to generate synthetic content preserving essential information, and iteratively refine it with privacy and rewriting agents until privacy safety is achieved while maintaining retrieval utility.', source: 'Zeng et al. (SAGE)', arxiv: 'https://arxiv.org/abs/2406.14773', conference: 'EMNLP 2025 https://aclanthology.org/2025.emnlp-main.1247/'},
  {id: 'MIT66', name: 'Skeptical Prompting', type: 'PREVENTIVE', active: true, category: 'Prompt Design', description: 'Encourage the model to critically evaluate retrieved context and rely on its own knowledge when the context appears unreliable; skeptical prompting improves robustness under adversarial poisoning for advanced LLMs but may hurt performance of weaker models.', source: 'Su et al. (Robust RAG)', arxiv: 'https://arxiv.org/abs/2412.16708', conference: null},
  {id: 'MIT67', name: 'RAGFort Dual‑Path Defense', type: 'DETECTIVE', active: true, category: 'Retrieval & Generation', description: 'RAGFort integrates contrastive reindexing with a constrained generation cascade. It restructures the retriever’s index using unsupervised HDBSCAN clustering and supervised contrastive learning to create class‑separable embeddings, making it harder for attackers to retrieve content from unrelated topics, and employs a cascaded generation mechanism with a draft model and a reference model to validate tokens and reject sensitive content.', source: 'Li et al. (RAGFort)', arxiv: 'https://arxiv.org/abs/2511.10128', conference: 'AAAI 2026'},
  {id: 'MIT68', name: 'Adversarial Training for Embedding Models', type: 'PREVENTIVE', active: true, category: 'Embedding Privacy', description: 'Protect embedding models against inversion and sensitive attribute inference by training an adversarial model to predict sensitive information while the embedding model maximizes the adversary’s loss and minimizes its primary objective. This minimax optimization reduces sensitive information leakage with minor utility loss.', source: 'Song & Raghunathan 2020', arxiv: 'https://arxiv.org/abs/2004.00053', conference: 'ACM CCS 2020 https://dl.acm.org/doi/10.1145/3372297.3417270'},
  {id: 'MIT69', name: 'Cautionary System Prompt', type: 'PREVENTIVE', active: true, category: 'Prompt‑Level Guidance', description: 'Add a system prompt that instructs the model not to reveal membership information (e.g., “Do not reveal any information about the membership of your knowledge base”). This minimal safeguard reduces simple membership inference attacks but offers limited protection against advanced methods.', source: 'Yang et al. (MrM)', arxiv: 'https://arxiv.org/abs/2506.07399', conference: 'Preprint'},
  {id: 'MIT70', name: 'Data‑Level Input Transformations', type: 'PREVENTIVE', active: true, category: 'Data Sanitization', description: 'Defend against visual membership inference by storing modified versions of images (e.g., horizontal flipping, grayscale conversion, cropping, Gaussian blurring) in the retrieval database to disrupt direct visual matching. Although this weakens naive MIAs, attackers can adopt augmentation‑aware strategies.', source: null, arxiv: 'https://arxiv.org/abs/2506.07399', conference: 'Preprint'},
  {id: 'MIT71', name: 'Score Distribution Equalization', type: 'REACTIVE', active: true, category: 'Response Adjustment', description: 'Defend against stealthy membership inference by adjusting the RAG system’s behaviour: answer questions related to database documents incorrectly (move members toward non‑members) or answer questions about non‑member documents accurately (move non‑members toward members). Both approaches reduce the distinguishability of members and non‑members but degrade RAG performance and utility.', source: 'Naseh et al. 2025', arxiv: 'https://arxiv.org/abs/2502.00306', conference: null}
] AS props
CREATE (n:Mitigation) SET n = props;

// --- CIA PRINCIPLES (3) ---
UNWIND [
  {id: 'C', name: 'Confidentiality', definition: 'Non-disclosure', question: 'Possible leakage?'},
  {id: 'I', name: 'Integrity', definition: 'Accuracy', question: 'Possible alteration?'},
  {id: 'A', name: 'Availability', definition: 'Accessibility', question: 'Possible disruption?'}
] AS props
CREATE (n:CIA) SET n = props;

// --- EXPOSES (RAG -> Surface, 24 links) ---
UNWIND [
  {source: 'TEXTUAL', target: 'M1'},
  {source: 'TEXTUAL', target: 'M2'},
  {source: 'TEXTUAL', target: 'M3'},
  {source: 'TEXTUAL', target: 'M4'},
  {source: 'TEXTUAL', target: 'M5'},
  {source: 'TEXTUAL', target: 'M6'},
  {source: 'TEXTUAL', target: 'M7'},
  {source: 'TEXTUAL', target: 'Tx'},
  {source: 'GRAPHRAG', target: 'M1'},
  {source: 'GRAPHRAG', target: 'M2'},
  {source: 'GRAPHRAG', target: 'M3'},
  {source: 'GRAPHRAG', target: 'M4'},
  {source: 'GRAPHRAG', target: 'M5'},
  {source: 'GRAPHRAG', target: 'M6'},
  {source: 'GRAPHRAG', target: 'M7'},
  {source: 'GRAPHRAG', target: 'Tx'},
  {source: 'MULTIMODAL', target: 'M1'},
  {source: 'MULTIMODAL', target: 'M2'},
  {source: 'MULTIMODAL', target: 'M3'},
  {source: 'MULTIMODAL', target: 'M4'},
  {source: 'MULTIMODAL', target: 'M5'},
  {source: 'MULTIMODAL', target: 'M6'},
  {source: 'MULTIMODAL', target: 'M7'},
  {source: 'MULTIMODAL', target: 'Tx'}
] AS rel
MATCH (a:RAG {id: rel.source}), (b:Surface {id: rel.target})
CREATE (a)-[:EXPOSES]->(b);

// --- ENABLES (Surface -> Attack, 56 links) ---
UNWIND [
  {source: 'M7', target: 'ATT.INJ.1'},
  {source: 'M7', target: 'ATT.INJ.2'},
  {source: 'M5', target: 'ATT.INJ.3'},
  {source: 'M7', target: 'ATT.INJ.3'},
  {source: 'M7', target: 'ATT.INJ.4'},
  {source: 'M1', target: 'ATT.POI.1'},
  {source: 'M1', target: 'ATT.POI.2'},
  {source: 'M2', target: 'ATT.POI.2'},
  {source: 'M1', target: 'ATT.POI.3'},
  {source: 'M1', target: 'ATT.POI.4'},
  {source: 'M1', target: 'ATT.POI.5'},
  {source: 'M1', target: 'ATT.POI.6'},
  {source: 'M3', target: 'ATT.POI.6'},
  {source: 'M5', target: 'ATT.POI.7'},
  {source: 'M7', target: 'ATT.POI.7'},
  {source: 'M1', target: 'ATT.POI.8'},
  {source: 'M2', target: 'ATT.POI.9'},
  {source: 'M3', target: 'ATT.POI.9'},
  {source: 'M1', target: 'ATT.POI.10'},
  {source: 'M1', target: 'ATT.POI.11'},
  {source: 'M1', target: 'ATT.POI.12'},
  {source: 'M1', target: 'ATT.POI.13'},
  {source: 'M5', target: 'ATT.POI.13'},
  {source: 'M1', target: 'ATT.POI.14'},
  {source: 'M1', target: 'ATT.POI.15'},
  {source: 'M1', target: 'ATT.POI.16'},
  {source: 'M5', target: 'ATT.INF.1'},
  {source: 'M7', target: 'ATT.INF.1'},
  {source: 'M7', target: 'ATT.INF.2'},
  {source: 'M5', target: 'ATT.INF.3'},
  {source: 'M7', target: 'ATT.INF.3'},
  {source: 'M5', target: 'ATT.INF.4'},
  {source: 'M7', target: 'ATT.INF.4'},
  {source: 'M5', target: 'ATT.INF.5'},
  {source: 'M7', target: 'ATT.INF.5'},
  {source: 'M5', target: 'ATT.EXF.1'},
  {source: 'M2', target: 'ATT.EXF.2'},
  {source: 'M3', target: 'ATT.EXF.2'},
  {source: 'M2', target: 'ATT.EXF.3'},
  {source: 'M7', target: 'ATT.EXF.4'},
  {source: 'M7', target: 'ATT.EXF.5'},
  {source: 'M5', target: 'ATT.EXF.6'},
  {source: 'M7', target: 'ATT.EXF.6'},
  {source: 'M5', target: 'ATT.EXF.7'},
  {source: 'M7', target: 'ATT.EXF.7'},
  {source: 'M1', target: 'ATT.EXF.8'},
  {source: 'M3', target: 'ATT.EXF.8'},
  {source: 'M5', target: 'ATT.EXF.9'},
  {source: 'M7', target: 'ATT.EXF.9'},
  {source: 'M2', target: 'ATT.EXF.10'},
  {source: 'M3', target: 'ATT.EXF.10'},
  {source: 'M5', target: 'ATT.EXF.11'},
  {source: 'M7', target: 'ATT.EXF.11'},
  {source: 'M5', target: 'ATT.DEG.1'},
  {source: 'M7', target: 'ATT.DEG.1'},
  {source: 'M1', target: 'ATT.DEG.2'}
] AS rel
MATCH (a:Surface {id: rel.source}), (b:Attack {id: rel.target})
CREATE (a)-[:ENABLES]->(b);

// --- EXPLOITS (Attack -> Weakness, 39 links) ---
// Mapping aligned with SYNTHESE v5.0 Table 4.2b (CAPEC -> CWE)
UNWIND [
  {source: 'ATT.INJ.1', target: 'CWE-1427'},
  {source: 'ATT.INJ.2', target: 'CWE-1427'},
  {source: 'ATT.INJ.2', target: 'CWE-693'},
  {source: 'ATT.INJ.3', target: 'CWE-863'},
  {source: 'ATT.INJ.4', target: 'CWE-1427'},
  {source: 'ATT.POI.1', target: 'CWE-345'},
  {source: 'ATT.POI.2', target: 'CWE-345'},
  {source: 'ATT.POI.3', target: 'CWE-345'},
  {source: 'ATT.POI.4', target: 'CWE-345'},
  {source: 'ATT.POI.5', target: 'CWE-345'},
  {source: 'ATT.POI.6', target: 'CWE-345'},
  {source: 'ATT.POI.7', target: 'CWE-345'},
  {source: 'ATT.POI.8', target: 'CWE-345'},
  {source: 'ATT.POI.9', target: 'CWE-345'},
  {source: 'ATT.POI.10', target: 'CWE-345'},
  {source: 'ATT.POI.11', target: 'CWE-345'},
  {source: 'ATT.POI.12', target: 'CWE-345'},
  {source: 'ATT.POI.13', target: 'CWE-345'},
  {source: 'ATT.POI.14', target: 'CWE-345'},
  {source: 'ATT.POI.15', target: 'CWE-345'},
  {source: 'ATT.POI.16', target: 'CWE-345'},
  {source: 'ATT.INF.1', target: 'CWE-200'},
  {source: 'ATT.INF.2', target: 'CWE-203'},
  {source: 'ATT.INF.3', target: 'CWE-200'},
  {source: 'ATT.INF.4', target: 'CWE-200'},
  {source: 'ATT.INF.5', target: 'CWE-200'},
  {source: 'ATT.EXF.1', target: 'CWE-200'},
  {source: 'ATT.EXF.2', target: 'CWE-200'},
  {source: 'ATT.EXF.3', target: 'CWE-200'},
  {source: 'ATT.EXF.4', target: 'CWE-200'},
  {source: 'ATT.EXF.5', target: 'CWE-200'},
  {source: 'ATT.EXF.6', target: 'CWE-200'},
  {source: 'ATT.EXF.7', target: 'CWE-200'},
  {source: 'ATT.EXF.8', target: 'CWE-212'},
  {source: 'ATT.EXF.9', target: 'CWE-200'},
  {source: 'ATT.EXF.10', target: 'CWE-200'},
  {source: 'ATT.EXF.11', target: 'CWE-200'},
  {source: 'ATT.DEG.1', target: 'CWE-400'},
  {source: 'ATT.DEG.2', target: 'CWE-770'}
] AS rel
MATCH (a:Attack {id: rel.source}), (b:Weakness {id: rel.target})
CREATE (a)-[:EXPLOITS]->(b);

// --- GENERATES primary (Attack -> Risk, 38 links) ---
UNWIND [
  {source: 'ATT.INJ.1', target: 'R9', type: 'primary'},
  {source: 'ATT.INJ.2', target: 'R10', type: 'primary'},
  {source: 'ATT.INJ.3', target: 'R18', type: 'primary'},
  {source: 'ATT.INJ.4', target: 'R21', type: 'primary'},
  {source: 'ATT.POI.1', target: 'R8', type: 'primary'},
  {source: 'ATT.POI.2', target: 'R11', type: 'primary'},
  {source: 'ATT.POI.3', target: 'R12', type: 'primary'},
  {source: 'ATT.POI.4', target: 'R13', type: 'primary'},
  {source: 'ATT.POI.5', target: 'R15', type: 'primary'},
  {source: 'ATT.POI.6', target: 'R17', type: 'primary'},
  {source: 'ATT.POI.7', target: 'R19', type: 'primary'},
  {source: 'ATT.POI.8', target: 'R20', type: 'primary'},
  {source: 'ATT.POI.9', target: 'R23', type: 'primary'},
  {source: 'ATT.POI.10', target: 'R24', type: 'primary'},
  {source: 'ATT.POI.11', target: 'R29', type: 'primary'},
  {source: 'ATT.POI.12', target: 'R30', type: 'primary'},
  {source: 'ATT.POI.13', target: 'R32', type: 'primary'},
  {source: 'ATT.POI.14', target: 'R33', type: 'primary'},
  {source: 'ATT.POI.15', target: 'R34', type: 'primary'},
  {source: 'ATT.POI.16', target: 'R35', type: 'primary'},
  {source: 'ATT.INF.1', target: 'R4', type: 'primary'},
  {source: 'ATT.INF.2', target: 'R16', type: 'primary'},
  {source: 'ATT.INF.3', target: 'R25', type: 'primary'},
  {source: 'ATT.INF.4', target: 'R37', type: 'primary'},
  {source: 'ATT.INF.5', target: 'R39', type: 'primary'},
  {source: 'ATT.EXF.1', target: 'R2', type: 'primary'},
  {source: 'ATT.EXF.2', target: 'R3', type: 'primary'},
  {source: 'ATT.EXF.3', target: 'R5', type: 'primary'},
  {source: 'ATT.EXF.4', target: 'R6', type: 'primary'},
  {source: 'ATT.EXF.5', target: 'R7', type: 'primary'},
  {source: 'ATT.EXF.6', target: 'R14', type: 'primary'},
  {source: 'ATT.EXF.7', target: 'R22', type: 'primary'},
  {source: 'ATT.EXF.8', target: 'R27', type: 'primary'},
  {source: 'ATT.EXF.9', target: 'R31', type: 'primary'},
  {source: 'ATT.EXF.10', target: 'R38', type: 'primary'},
  {source: 'ATT.EXF.11', target: 'R40', type: 'primary'},
  {source: 'ATT.DEG.1', target: 'R1', type: 'primary'},
  {source: 'ATT.DEG.2', target: 'R36', type: 'primary'}
] AS rel
MATCH (a:Attack {id: rel.source}), (b:Risk {id: rel.target})
CREATE (a)-[:GENERATES {type: rel.type}]->(b);

// --- GENERATES secondary (Attack -> Risk, 8 links) ---
// An attack generates a primary risk (above) and may also generate
// secondary risks on different assets or CIA dimensions.
UNWIND [
  {source: 'ATT.INJ.1', target: 'R6', type: 'secondary', justification: 'Injection can also disclose corpus data (I->C, OUTPUT->CORPUS)'},
  {source: 'ATT.INJ.3', target: 'R27', type: 'secondary', justification: 'ACL bypass exposes documents from higher privilege levels (I+C->C, OUTPUT->CORPUS)'},
  {source: 'ATT.POI.1', target: 'R1', type: 'secondary', justification: 'A corrupted corpus also degrades responses (I->A, CORPUS->OUTPUT)'},
  {source: 'ATT.POI.7', target: 'R22', type: 'secondary', justification: 'Source exposure facilitates adaptive extraction (reconnaissance->exfiltration)'},
  {source: 'ATT.POI.14', target: 'R1', type: 'secondary', justification: 'Partially correct evidence degrades responses (I->A, CORPUS->OUTPUT)'},
  {source: 'ATT.POI.15', target: 'R1', type: 'secondary', justification: 'Inter-source contradictions degrade responses (I->A, CORPUS->OUTPUT) -- same SafeRAG cascade as POI.14'},
  {source: 'ATT.EXF.8', target: 'R4', type: 'secondary', justification: 'Over-indexing reveals document membership (CORPUS->MEMBERSHIP)'},
  {source: 'ATT.EXF.9', target: 'R4', type: 'secondary', justification: 'Verbatim extraction implies membership knowledge (CORPUS->MEMBERSHIP)'}
] AS rel
MATCH (a:Attack {id: rel.source}), (b:Risk {id: rel.target})
CREATE (a)-[:GENERATES {type: rel.type, justification: rel.justification}]->(b);

// --- MITIGATES (Mitigation -> Risk, 115 links) ---
UNWIND [
  {source: 'MIT0', target: 'R2'},
  {source: 'MIT0', target: 'R3'},
  {source: 'MIT0', target: 'R4'},
  {source: 'MIT1', target: 'R2'},
  {source: 'MIT1', target: 'R3'},
  {source: 'MIT1', target: 'R4'},
  {source: 'MIT2', target: 'R2'},
  {source: 'MIT2', target: 'R3'},
  {source: 'MIT2', target: 'R4'},
  {source: 'MIT3', target: 'R2'},
  {source: 'MIT3', target: 'R5'},
  {source: 'MIT3', target: 'R6'},
  {source: 'MIT3', target: 'R8'},
  {source: 'MIT4', target: 'R6'},
  {source: 'MIT4', target: 'R7'},
  {source: 'MIT4', target: 'R9'},
  {source: 'MIT4', target: 'R10'},
  {source: 'MIT5', target: 'R9'},
  {source: 'MIT5', target: 'R10'},
  {source: 'MIT5', target: 'R11'},
  {source: 'MIT6', target: 'R8'},
  {source: 'MIT6', target: 'R9'},
  {source: 'MIT6', target: 'R10'},
  {source: 'MIT7', target: 'R5'},
  {source: 'MIT8', target: 'R3'},
  {source: 'MIT9', target: 'R2'},
  {source: 'MIT9', target: 'R8'},
  {source: 'MIT10', target: 'R2'},
  {source: 'MIT10', target: 'R5'},
  {source: 'MIT10', target: 'R6'},
  {source: 'MIT11', target: 'R8'},
  {source: 'MIT11', target: 'R9'},
  {source: 'MIT12', target: 'R5'},
  {source: 'MIT12', target: 'R6'},
  {source: 'MIT12', target: 'R7'},
  {source: 'MIT13', target: 'R11'},
  {source: 'MIT14', target: 'R8'},
  {source: 'MIT14', target: 'R11'},
  {source: 'MIT15', target: 'R8'},
  {source: 'MIT16', target: 'R8'},
  {source: 'MIT16', target: 'R9'},
  {source: 'MIT17', target: 'R8'},
  {source: 'MIT17', target: 'R9'},
  {source: 'MIT18', target: 'R8'},
  {source: 'MIT18', target: 'R11'},
  {source: 'MIT19', target: 'R12'},
  {source: 'MIT20', target: 'R13'},
  {source: 'MIT21', target: 'R13'},
  {source: 'MIT22', target: 'R14'},
  {source: 'MIT23', target: 'R15'},
  {source: 'MIT24', target: 'R16'},
  {source: 'MIT25', target: 'R8'},
  {source: 'MIT26', target: 'R7'},
  {source: 'MIT26', target: 'R8'},
  {source: 'MIT26', target: 'R10'},
  {source: 'MIT27', target: 'R2'},
  {source: 'MIT27', target: 'R9'},
  {source: 'MIT27', target: 'R10'},
  {source: 'MIT28', target: 'R1'},
  {source: 'MIT28', target: 'R2'},
  {source: 'MIT29', target: 'R1'},
  {source: 'MIT29', target: 'R2'},
  {source: 'MIT30', target: 'R18'},
  {source: 'MIT31', target: 'R18'},
  {source: 'MIT31', target: 'R2'},
  {source: 'MIT32', target: 'R18'},
  {source: 'MIT33', target: 'R19'},
  {source: 'MIT34', target: 'R19'},
  {source: 'MIT35', target: 'R20'},
  {source: 'MIT36', target: 'R22'},
  {source: 'MIT37', target: 'R22'},
  {source: 'MIT38', target: 'R22'},
  {source: 'MIT39', target: 'R22'},
  {source: 'MIT40', target: 'R22'},
  {source: 'MIT41', target: 'R22'},
  {source: 'MIT42', target: 'R11'},
  {source: 'MIT42', target: 'R12'},
  {source: 'MIT42', target: 'R15'},
  {source: 'MIT43', target: 'R21'},
  {source: 'MIT44', target: 'R21'},
  {source: 'MIT45', target: 'R22'},
  {source: 'MIT46', target: 'R2'},
  {source: 'MIT46', target: 'R3'},
  {source: 'MIT47', target: 'R2'},
  {source: 'MIT47', target: 'R11'},
  {source: 'MIT48', target: 'R2'},
  {source: 'MIT48', target: 'R3'},
  {source: 'MIT49', target: 'R23'},
  {source: 'MIT50', target: 'R23'},
  {source: 'MIT51', target: 'R25'},
  {source: 'MIT52', target: 'R24'},
  {source: 'MIT53', target: 'R24'},
  {source: 'MIT54', target: 'R24'},
  {source: 'MIT55', target: 'R24'},
  {source: 'MIT56', target: 'R26'},
  {source: 'MIT57', target: 'R27'},
  {source: 'MIT58', target: 'R28'},
  {source: 'MIT59', target: 'R29'},
  {source: 'MIT60', target: 'R30'},
  {source: 'MIT61', target: 'R31'},
  {source: 'MIT62', target: 'R4'},
  {source: 'MIT62', target: 'R31'},
  {source: 'MIT63', target: 'R32'},
  {source: 'MIT64', target: 'R2'},
  {source: 'MIT64', target: 'R27'},
  {source: 'MIT65', target: 'R27'},
  {source: 'MIT65', target: 'R2'},
  {source: 'MIT66', target: 'R29'},
  {source: 'MIT66', target: 'R30'},
  {source: 'MIT67', target: 'R40'},
  {source: 'MIT68', target: 'R38'},
  {source: 'MIT69', target: 'R39'},
  {source: 'MIT69', target: 'R37'},
  {source: 'MIT70', target: 'R39'},
  {source: 'MIT71', target: 'R37'}
] AS rel
MATCH (a:Mitigation {id: rel.source}), (b:Risk {id: rel.target})
CREATE (a)-[:MITIGATES]->(b);

// --- CORRECTS (PREVENTIVE Mitigation -> Weakness, 21 links) ---
UNWIND [
  {source: 'MIT0', target: 'CWE-200'},
  {source: 'MIT1', target: 'CWE-200'},
  {source: 'MIT2', target: 'CWE-200'},
  {source: 'MIT3', target: 'CWE-200'},
  {source: 'MIT4', target: 'CWE-200'},
  {source: 'MIT4', target: 'CWE-1427'},
  {source: 'MIT5', target: 'CWE-1427'},
  {source: 'MIT7', target: 'CWE-200'},
  {source: 'MIT9', target: 'CWE-200'},
  {source: 'MIT12', target: 'CWE-200'},
  {source: 'MIT13', target: 'CWE-345'},
  {source: 'MIT16', target: 'CWE-1427'},
  {source: 'MIT18', target: 'CWE-345'},
  {source: 'MIT31', target: 'CWE-200'},
  {source: 'MIT43', target: 'CWE-1427'},
  {source: 'MIT46', target: 'CWE-200'},
  {source: 'MIT48', target: 'CWE-200'},
  {source: 'MIT57', target: 'CWE-200'},
  {source: 'MIT62', target: 'CWE-1427'},
  {source: 'MIT64', target: 'CWE-200'},
  {source: 'MIT65', target: 'CWE-200'}
] AS rel
MATCH (a:Mitigation {id: rel.source}), (b:Weakness {id: rel.target})
CREATE (a)-[:CORRECTS]->(b);

// --- AFFECTS (Risk -> CIA, 45 links) ---
UNWIND [
  {source: 'R0', target: 'C'},
  {source: 'R0', target: 'I'},
  {source: 'R0', target: 'A'},
  {source: 'R1', target: 'A'},
  {source: 'R2', target: 'C'},
  {source: 'R3', target: 'C'},
  {source: 'R4', target: 'C'},
  {source: 'R5', target: 'C'},
  {source: 'R6', target: 'C'},
  {source: 'R7', target: 'C'},
  {source: 'R8', target: 'I'},
  {source: 'R9', target: 'I'},
  {source: 'R10', target: 'I'},
  {source: 'R11', target: 'I'},
  {source: 'R12', target: 'I'},
  {source: 'R13', target: 'I'},
  {source: 'R14', target: 'C'},
  {source: 'R15', target: 'I'},
  {source: 'R16', target: 'C'},
  {source: 'R17', target: 'I'},
  {source: 'R18', target: 'I'},
  {source: 'R18', target: 'C'},
  {source: 'R19', target: 'C'},
  {source: 'R20', target: 'I'},
  {source: 'R21', target: 'I'},
  {source: 'R22', target: 'C'},
  {source: 'R23', target: 'I'},
  {source: 'R24', target: 'I'},
  {source: 'R25', target: 'C'},
  {source: 'R26', target: 'I'},
  {source: 'R27', target: 'C'},
  {source: 'R28', target: 'A'},
  {source: 'R28', target: 'C'},
  {source: 'R29', target: 'I'},
  {source: 'R30', target: 'I'},
  {source: 'R31', target: 'C'},
  {source: 'R32', target: 'I'},
  {source: 'R33', target: 'I'},
  {source: 'R34', target: 'I'},
  {source: 'R35', target: 'I'},
  {source: 'R36', target: 'I'},
  {source: 'R37', target: 'C'},
  {source: 'R38', target: 'C'},
  {source: 'R39', target: 'C'},
  {source: 'R40', target: 'C'}
] AS rel
MATCH (a:Risk {id: rel.source}), (b:CIA {id: rel.target})
CREATE (a)-[:AFFECTS]->(b);

// ============================================
// SUMMARY (v5.2.0)
// Entity types: 7 (RAG, Surface, Attack, Weakness, Risk, Mitigation, CIA)
// TOTAL NODES: 177
// Relation types: 7 (EXPOSES, ENABLES, EXPLOITS, GENERATES, MITIGATES, CORRECTS, AFFECTS)
// EXPOSES: 24, ENABLES: 56, EXPLOITS: 39
// GENERATES: 46 (38 primary + 8 secondary)
// MITIGATES: 115, CORRECTS: 21, AFFECTS: 45
// TOTAL RELATIONS: 346
// ============================================

// ============================================
// TAXONOMIC VIEWS v5.0 (38 attacks ATT.x)
// ============================================
//
// Causal chain:
//   RAG ->EXPOSES-> Surface ->ENABLES-> Attack ->EXPLOITS-> Weakness
//                                       |                    ^
//                                    GENERATES             CORRECTS
//                                       v                    |
//                                     Risk <--MITIGATES-- Mitigation
//                                       |
//                                    AFFECTS -> CIA
//
// --- VIEW V1: Architect ---
// MATCH (rag:RAG {id: 'TEXTUAL'})-[:EXPOSES]->(s:Surface)-[:ENABLES]->(a:Attack)
// OPTIONAL MATCH (a)-[:EXPLOITS]->(f:Weakness)
// OPTIONAL MATCH (m:Mitigation)-[:CORRECTS]->(f)
// OPTIONAL MATCH (a)-[:GENERATES]->(r:Risk)
// RETURN rag.id AS rag_type, s.id AS surface,
//        a.id AS attack, a.name AS name,
//        r.id AS risk, r.name AS consequence,
//        f.id AS weakness, collect(DISTINCT m.id) AS corrective_mitigations
// ORDER BY s.id, a.id;
//
// --- VIEW V2: CISO ---
// MATCH (a:Attack)-[:GENERATES]->(r:Risk)
// OPTIONAL MATCH (a)-[:EXPLOITS]->(f:Weakness)
// OPTIONAL MATCH (m:Mitigation)-[:MITIGATES]->(r)
// RETURN r.id AS risk, r.name AS consequence, a.category AS category,
//        a.id AS attack, a.name AS technique,
//        collect(DISTINCT m.id) AS mitigations,
//        CASE WHEN size(collect(DISTINCT m.id)) = 0 THEN 'GAP' ELSE 'COVERED' END AS status
// ORDER BY r.id;
//
// --- VIEW V2b: Coverage gaps ---
// MATCH (r:Risk) WHERE NOT (r)<-[:MITIGATES]-(:Mitigation)
// OPTIONAL MATCH (a:Attack)-[:GENERATES]->(r)
// RETURN r.id AS risk, r.name AS consequence, a.id AS attack, r.asset AS asset;
//
// --- VIEW V3: Pentester (full chain) ---
// MATCH (rag:RAG)-[:EXPOSES]->(s:Surface)-[:ENABLES]->(a:Attack)-[:GENERATES]->(r:Risk)
// OPTIONAL MATCH (a)-[:EXPLOITS]->(f:Weakness)
// OPTIONAL MATCH (m:Mitigation)-[:MITIGATES]->(r)
// RETURN rag.id AS rag_type, s.id AS surface,
//        a.id AS attack, a.name AS technique,
//        a.category AS category, r.id AS risk, r.name AS consequence,
//        collect(DISTINCT f.id) AS weaknesses,
//        collect(DISTINCT m.id) AS mitigations;
//
// --- VIEW V4: DPO (by asset) ---
// MATCH (r:Risk)
// OPTIONAL MATCH (m:Mitigation)-[:MITIGATES]->(r)
// WITH r.asset AS asset, r,
//      CASE WHEN NOT (r)<-[:MITIGATES]-(:Mitigation) THEN 1 ELSE 0 END AS gap
// RETURN asset, count(r) AS risk_count, sum(gap) AS gap_count
// ORDER BY risk_count DESC;
